### ISSUE TITLE
ImportError: cannot import name blocks

### ISSUE THREAD

**Issue by avatar-lavventura** [pipermerriam/populus#301] opened 2017-06-25 14:09 UTC
platform darwin -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/alper/pop, inifile:
plugins: populus-1.6.9

I have installed solc’s latest version:
```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity
brew linkapps solidity
```

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.11+commit.68ef5810.Darwin.appleclang

$ python --version
Python 3.6.1
```

**Did following:**
```
brew install pkg-config libffi autoconf automake libtool openssl
pip install web3
pip install eth-testrpc 
pip install eth-testrpc --upgrade

sudo pip install pytest==3.1.2
sudo pip install py==1.4.34
```

```
mkdir populus
cd populus
populus init
py.test --capture=fd tests/test_greeter.py -s 
```

Gives following error:
```
____________________________________________________ ERROR at setup of test_greeter _____________________________________________________

project = <populus.project.Project object at 0x105089a10>

    @pytest.yield_fixture()
    def chain(project):
>       with project.get_chain('tester') as chain:

/usr/local/lib/python2.7/site-packages/populus/plugin.py:27:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python2.7/site-packages/populus/chain/tester.py:13: in __enter__
    self.rpc_methods = self.web3.currentProvider.rpc_methods
/usr/local/lib/python2.7/site-packages/populus/utils/functional.py:27: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
/usr/local/lib/python2.7/site-packages/populus/chain/base.py:96: in web3
    return self.web3_config.get_web3()
/usr/local/lib/python2.7/site-packages/populus/config/web3.py:65: in get_web3
    web3 = Web3(self.provider)
/usr/local/lib/python2.7/site-packages/populus/config/web3.py:54: in provider
    return self.provider_class(**self.provider_kwargs)
/usr/local/lib/python2.7/site-packages/web3/providers/tester.py:24: in __init__
    from testrpc.rpc import RPCMethods
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import sys
    import logging

    import rlp

    try:
        from sha3 import keccak_256
    except ImportError:
        from sha3 import sha3_256 as keccak_256

>   from ethereum import blocks
E   ImportError: cannot import name blocks

/usr/local/lib/python2.7/site-packages/testrpc/rpc.py:11: ImportError
________________________________________________ ERROR at setup of test_custom_greeting _________________________________________________

project = <populus.project.Project object at 0x105089a10>

    @pytest.yield_fixture()
    def chain(project):
>       with project.get_chain('tester') as chain:

/usr/local/lib/python2.7/site-packages/populus/plugin.py:27:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python2.7/site-packages/populus/chain/tester.py:13: in __enter__
    self.rpc_methods = self.web3.currentProvider.rpc_methods
/usr/local/lib/python2.7/site-packages/populus/utils/functional.py:27: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
/usr/local/lib/python2.7/site-packages/populus/chain/base.py:96: in web3
    return self.web3_config.get_web3()
/usr/local/lib/python2.7/site-packages/populus/config/web3.py:65: in get_web3
    web3 = Web3(self.provider)
/usr/local/lib/python2.7/site-packages/populus/config/web3.py:54: in provider
    return self.provider_class(**self.provider_kwargs)
/usr/local/lib/python2.7/site-packages/web3/providers/tester.py:24: in __init__
    from testrpc.rpc import RPCMethods
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import sys
    import logging

    import rlp

    try:
        from sha3 import keccak_256
    except ImportError:
        from sha3 import sha3_256 as keccak_256

>   from ethereum import blocks
E   ImportError: cannot import name blocks

/usr/local/lib/python2.7/site-packages/testrpc/rpc.py:11: ImportError
======================================================== 2 error in 0.38 seconds =======================================================
```

<img width="599" alt="screen shot 2017-06-25 at 17 57 11" src="https://user-images.githubusercontent.com/18537398/27517138-c42e01a4-59cf-11e7-9b07-f6ab09e40f33.png">

**Comment by ice09** [comment] 2017-06-25 15:33
for workaround compare #300

**Comment by avatar-lavventura** [comment] 2017-06-25 15:40
`pip uninstall ethereum  &&  pip install ethereum==1.6.1` Fixed it. @ice09

**Comment by pipermerriam** [comment] 2017-06-26 15:10
Support for newest pyethereum will be underway soon.

**Comment by pipermerriam** [comment] 2017-06-28 21:51
Marking as duplicate of #300

**Closed by pipermerriam** 2017-06-28 21:51 UTC
