### ISSUE TITLE
 ImportError: cannot import name 'blocks'

### ISSUE THREAD

**Issue by Netherdrake** [pipermerriam/populus#305] opened 2017-07-06 08:50 UTC
* Populus Version: 1.6.9
* OS: Arch Linux, Anaconda Python 3.6.1

### What was wrong?
It throws an exception: `ImportError: cannot import name 'blocks'`.

## Re-create:
```
mkdir greeter && cd greeter
populus init
py.test tests/
```

## Full Output
```
~/G/t/greeter % populus init
Wrote default populus configuration to `./populus.json`.
Created Directory: ./contracts
Created Example Contract: ./contracts/Greeter.sol
Created Directory: ./tests
Created Example Tests: ./tests/test_greeter.py
~/G/t/greeter % py.test tests/
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.6.1, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: /home/user/GitHub/tmp/greeter, inifile:
plugins: populus-1.6.9, celery-4.0.2
collected 2 items 

tests/test_greeter.py EE

======================================================================================== ERRORS =========================================================================================
____________________________________________________________________________ ERROR at setup of test_greeter _____________________________________________________________________________

project = <populus.project.Project object at 0x7fde832e2668>

    @pytest.yield_fixture()
    def chain(project):
>       with project.get_chain('tester') as chain:

../../../anaconda3/lib/python3.6/site-packages/populus/plugin.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../anaconda3/lib/python3.6/site-packages/populus/chain/tester.py:13: in __enter__
    self.rpc_methods = self.web3.currentProvider.rpc_methods
../../../anaconda3/lib/python3.6/site-packages/populus/utils/functional.py:27: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
../../../anaconda3/lib/python3.6/site-packages/populus/chain/base.py:96: in web3
    return self.web3_config.get_web3()
../../../anaconda3/lib/python3.6/site-packages/populus/config/web3.py:65: in get_web3
    web3 = Web3(self.provider)
../../../anaconda3/lib/python3.6/site-packages/populus/config/web3.py:54: in provider
    return self.provider_class(**self.provider_kwargs)
../../../anaconda3/lib/python3.6/site-packages/web3/providers/tester.py:24: in __init__
    from testrpc.rpc import RPCMethods
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import sys
    import logging
    
    import rlp
    
    try:
        from sha3 import keccak_256
    except ImportError:
        from sha3 import sha3_256 as keccak_256
    
>   from ethereum import blocks
E   ImportError: cannot import name 'blocks'

../../../anaconda3/lib/python3.6/site-packages/testrpc/rpc.py:11: ImportError
________________________________________________________________________ ERROR at setup of test_custom_greeting _________________________________________________________________________

project = <populus.project.Project object at 0x7fde832e2668>

    @pytest.yield_fixture()
    def chain(project):
>       with project.get_chain('tester') as chain:

../../../anaconda3/lib/python3.6/site-packages/populus/plugin.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../anaconda3/lib/python3.6/site-packages/populus/chain/tester.py:13: in __enter__
    self.rpc_methods = self.web3.currentProvider.rpc_methods
../../../anaconda3/lib/python3.6/site-packages/populus/utils/functional.py:27: in __get__
    res = instance.__dict__[self.name] = self.func(instance)
../../../anaconda3/lib/python3.6/site-packages/populus/chain/base.py:96: in web3
    return self.web3_config.get_web3()
../../../anaconda3/lib/python3.6/site-packages/populus/config/web3.py:65: in get_web3
    web3 = Web3(self.provider)
../../../anaconda3/lib/python3.6/site-packages/populus/config/web3.py:54: in provider
    return self.provider_class(**self.provider_kwargs)
../../../anaconda3/lib/python3.6/site-packages/web3/providers/tester.py:24: in __init__
    from testrpc.rpc import RPCMethods
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import sys
    import logging
    
    import rlp
    
    try:
        from sha3 import keccak_256
    except ImportError:
        from sha3 import sha3_256 as keccak_256
    
>   from ethereum import blocks
E   ImportError: cannot import name 'blocks'

../../../anaconda3/lib/python3.6/site-packages/testrpc/rpc.py:11: ImportError
================================================================================ 2 error in 0.32 seconds ================================================================================
```

#### Cute Animal Picture

![](https://i.cbc.ca/1.3651819.1466797901!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_1180/dog-in-car.jpg)

**Comment by Netherdrake** [comment] 2017-07-06 09:11
I tried downgrading ethereum:
```
pip install --force-reinstall --no-deps git+https://github.com/ethereum/pyethereum@19b57e9b2db65874e4a2fe44dbb1dc9021350f42
```

Although now I get a different error:
```
~/G/t/greeter % py.test tests/
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.6.1, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: /home/user/GitHub/tmp/greeter, inifile:
plugins: celery-4.0.2
collected 2 items 

tests/test_greeter.py EE

======================================================================================== ERRORS =========================================================================================
____________________________________________________________________________ ERROR at setup of test_greeter _____________________________________________________________________________
file /home/user/GitHub/tmp/greeter/tests/test_greeter.py, line 1
  def test_greeter(chain):
E       fixture 'chain' not found
>       available fixtures: cache, capfd, capsys, celery_app, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, depends_on_current_app, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory, use_celery_app_trap
>       use 'pytest --fixtures [testpath]' for help on them.

/home/user/GitHub/tmp/greeter/tests/test_greeter.py:1
________________________________________________________________________ ERROR at setup of test_custom_greeting _________________________________________________________________________
file /home/user/GitHub/tmp/greeter/tests/test_greeter.py, line 8
  def test_custom_greeting(chain):
E       fixture 'chain' not found
>       available fixtures: cache, capfd, capsys, celery_app, celery_config, celery_enable_logging, celery_includes, celery_parameters, celery_session_app, celery_session_worker, celery_worker, celery_worker_parameters, celery_worker_pool, depends_on_current_app, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory, use_celery_app_trap
>       use 'pytest --fixtures [testpath]' for help on them.

/home/user/GitHub/tmp/greeter/tests/test_greeter.py:8
================================================================================ 2 error in 0.02 seconds ================================================================================
~/G/t/greeter % 

```

**Comment by ice09** [comment] 2017-07-06 13:05
see #300 that worked for me.

**Comment by pipermerriam** [comment] 2017-07-06 18:47
This is duplicate of https://github.com/pipermerriam/populus/issues/300

Fix is in the works but it still may be a bit before this will work on `ethereum>=2.0.0`.  Hotfix incoming to pin `etheeum<2.0.0` so that `eth-testrpc` will be happy.

**Closed by pipermerriam** 2017-07-06 18:47 UTC
